# Generated by Django 4.2 on 2023-06-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('students', '0003_alter_studentpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='adminstrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.adminstrator'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
