# Generated by Django 4.2 on 2023-06-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='effec',
            new_name='effect',
        ),
    ]
