# Generated by Django 4.2 on 2023-06-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_rename_effec_socialmedia_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='effect',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
