# Generated by Django 4.2 on 2023-06-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_socialmedia_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusage',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.service')),
                ('service_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.serviceusage')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.serviceuser')),
            ],
            options={
                'verbose_name_plural': 'Service Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
