# Generated by Django 4.2 on 2023-06-18 17:52

from django.db import migrations, models
import django.db.models.deletion
import marketing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_serviceusage_payment_done_servicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[marketing.validators.validate_service_payment_amount]),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.service', validators=[marketing.validators.validate_services]),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='service_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.serviceuser', validators=[marketing.validators.validate_service_payment_user]),
        ),
    ]
