# Generated by Django 4.2 on 2023-06-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminstrator',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Admintrators'},
        ),
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bosses'},
        ),
    ]
