# Generated by Django 4.2 on 2023-06-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_adminstrator_options_alter_boss_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminstrator',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Admintrators'},
        ),
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bosses'},
        ),
    ]
